contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bigstitcher channel"
    url: https://nfcore.slack.com/channels/bigstitcher
    about: Discussion about the JaneliaSciComp/nf-BigStitcher-Spark pipeline
